# Generated by Django 4.0.10 on 2023-04-11 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=700, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('transaction_reason', models.CharField(choices=[('VERIFY DEBIT CARD', 'VERIFY DEBIT CARD'), ('WALLET DEPOSIT', 'WALLET DEPOSIT'), ('WALLET WITHDRAWAL', 'WALLET WITHDRAWAL'), ('PROFIT EARNED', 'PROFIT EARNED'), ('TRIP EARNED', 'TRIP EARNED'), ('TICKET PAYMENT', 'TICKET PAYMENT')], default='WALLET DEPOSIT', max_length=50, verbose_name='Transaction Reason')),
                ('transaction_status', models.CharField(choices=[('PAID', 'PAID'), ('OWEING', 'OWEING'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], default='PAID', max_length=15, verbose_name='Transaction Status')),
                ('ref_code', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Transactions',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
    ]
