# Generated by Django 3.2.15 on 2022-10-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_banks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(max_length=500, unique=False),
        ),
    ]
