# Generated by Django 3.2.15 on 2022-10-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_banks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'United States Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('DKK', 'Danish Krone'), ('SEK', 'Swedish Krona'), ('ZAR', 'South African Rand'), ('AED', 'United Arab Emirates Dirham')], default='USD', max_length=3),
        ),
    ]
