# Generated by Django 4.0.10 on 2023-04-22 23:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dropsride.utils.validators
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=500, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['title'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Career Title')),
                ('summary', tinymce.models.HTMLField(blank=True, max_length=255, verbose_name='Career Summary')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Career Keywords')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('competency', models.CharField(blank=True, max_length=255)),
                ('content', tinymce.models.HTMLField(verbose_name='Career Content')),
                ('published_date', models.DateField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, verbose_name='Slug')),
                ('draft', models.BooleanField(default=True, verbose_name='Draft/Published')),
                ('location', models.ManyToManyField(to='settings.localization')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.teams')),
            ],
            options={
                'verbose_name': 'Careers',
                'verbose_name_plural': 'Careers',
                'ordering': ['-published_date', '-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(blank=True, max_length=500)),
                ('middle_name', models.CharField(blank=True, max_length=500)),
                ('last_name', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('NON-BINARY', 'NON-BINARY')], default='NON-BINARY', max_length=15)),
                ('age', models.CharField(choices=[('U21', 'U21'), ('U25', 'U25'), ('U34', 'U34'), ('U44', 'U44'), ('U54', 'U54'), ('U64', 'U64'), ('O65', 'O65')], default='U21', max_length=6)),
                ('file', models.FileField(upload_to='applicants/cv', validators=[dropsride.utils.validators.validate_uploaded_pdf_extension])),
                ('cover_letter', tinymce.models.HTMLField()),
                ('disability', models.BooleanField(default=False)),
                ('consent', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries_plus.country', verbose_name='Country')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.localization')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_position', to='careers.careers')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
    ]
