# Generated by Django 3.2.15 on 2022-10-20 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_auto_20221017_0258'),
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers',
            name='location',
        ),
        migrations.AddField(
            model_name='careers',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitesettings.localization'),
        ),
    ]
