# Generated by Django 4.0.10 on 2023-04-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='careers',
            managers=[
            ],
        ),
    ]
