# Generated by Django 3.2.15 on 2022-10-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20221020_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, verbose_name='Slug'),
        ),
    ]
