# Generated by Django 3.2.15 on 2022-10-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0004_auto_20221020_0324'),
        ('careers', '0003_teams_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers',
            name='location',
        ),
        migrations.AddField(
            model_name='careers',
            name='location',
            field=models.ManyToManyField(null=True, to='sitesettings.Localization'),
        ),
    ]
