# Generated by Django 3.2.15 on 2022-10-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0005_auto_20221020_1056'),
        ('careers', '0004_auto_20221020_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='location',
            field=models.ManyToManyField(to='sitesettings.Localization'),
        ),
    ]
