# Generated by Django 3.2.15 on 2022-10-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20221018_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytransactionhistory',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Company Transaction History', 'verbose_name_plural': 'Companys Transaction Histories'},
        ),
        migrations.AlterModelOptions(
            name='companywallet',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Company Wallet', 'verbose_name_plural': 'Companys Wallet'},
        ),
    ]
