# Generated by Django 3.2.15 on 2022-10-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companywallet_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
