# Generated by Django 4.0.10 on 2023-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE'), ('NON BINARY', 'NON BINARY')], default='NON BINARY', max_length=15, verbose_name='Gender'),
        ),
    ]
