# Generated by Django 4.0.10 on 2023-04-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextofkin',
            old_name='kin_verifed',
            new_name='kin_verified',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_verifed',
            new_name='profile_verified',
        ),
        migrations.AddField(
            model_name='registeredvehicles',
            name='vehicle_verified',
            field=models.BooleanField(default=False),
        ),
    ]
