# Generated by Django 4.0.10 on 2023-04-14 15:00

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_kin_verifed_nextofkin_kin_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bvn',
            field=models.CharField(blank=True, max_length=12, verbose_name='Bank Verification Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='user/passport', verbose_name='Display Photo'),
        ),
    ]
