# Generated by Django 4.0.10 on 2023-04-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bvn_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcards',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
