# Generated by Django 4.0.10 on 2023-04-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_savedcards_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedcards',
            old_name='card_verified',
            new_name='card_is_verified',
        ),
    ]
