# Generated by Django 3.2.15 on 2022-10-05 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_banks'),
        ('users', '0004_auto_20220930_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='user/passport', verbose_name='Display Photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='UserNextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text="ensure the name 'corresponds/is exactly' the same with their registered BVN", max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='user/nok/passport', verbose_name='Passport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Next of Kin',
                'verbose_name_plural': 'Users Next of Kin',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SavedCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name_on_card', models.CharField(max_length=255)),
                ('card_no', models.CharField(max_length=18)),
                ('card_exp_month', models.PositiveSmallIntegerField()),
                ('card_exp_year', models.PositiveSmallIntegerField()),
                ('expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Saved Card',
                'verbose_name_plural': 'User Saved Cards',
                'ordering': ['-card_no'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('acc_no', models.CharField(max_length=17)),
                ('acc_name', models.CharField(max_length=255)),
                ('bvn', models.CharField(max_length=11)),
                ('verified', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_account', to='currency.banks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Saved Bank',
                'verbose_name_plural': 'User Saved Banks',
                'ordering': ['-acc_name', 'verified'],
                'managed': True,
            },
        ),
    ]
