# Generated by Django 3.2.15 on 2022-10-17 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcards',
            name='expired',
        ),
        migrations.AddField(
            model_name='savedcards',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='VerifiedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('verified_code', models.CharField(blank=True, max_length=4, null=True)),
                ('verfied', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verified_phone', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verified Phone Number',
                'verbose_name_plural': 'Verified Phone Numbers',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
