# Generated by Django 3.2.15 on 2022-10-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221018_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifiedphone',
            old_name='verfied',
            new_name='verified',
        ),
    ]
