# Generated by Django 3.2.15 on 2022-10-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_verfied_verifiedphone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedphone',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
