# Generated by Django 3.2.15 on 2022-10-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_verifiedphone_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedphone',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
