# Generated by Django 3.2.15 on 2022-10-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_verifiedphone_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcards',
            name='card_provider',
            field=models.CharField(default='master', max_length=40),
        ),
    ]
