# Generated by Django 3.2.15 on 2022-10-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_savedcards_card_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcards',
            name='cvv',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
