# Generated by Django 3.2.15 on 2022-10-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_savedcards_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernextofkin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usernextofkin',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
