# Generated by Django 3.2.15 on 2022-10-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20221026_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcards',
            name='card_exp_month',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='savedcards',
            name='card_exp_year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
