# Generated by Django 3.2.15 on 2022-10-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20221027_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcards',
            name='card_no',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
