# Generated by Django 3.2.15 on 2022-10-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_savedcards_card_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedcards',
            options={'managed': True, 'ordering': ['-created', 'active'], 'verbose_name': 'User Saved Card', 'verbose_name_plural': 'User Saved Cards'},
        ),
    ]
