# Generated by Django 3.2.15 on 2022-10-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_savedcards_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'managed': True, 'ordering': ['-modified', 'verified'], 'verbose_name': 'User Saved Bank', 'verbose_name_plural': 'User Saved Banks'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='acc_no',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
