# Generated by Django 3.2.15 on 2022-10-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_auto_20221005_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridersavedaddress',
            name='captcha_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ridersavedaddress',
            name='post_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ridersavedaddress',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ridersavedaddress',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ridersavedaddress',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ridersavedaddress',
            name='latitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ridersavedaddress',
            name='longitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ridersavedaddress',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
