# Generated by Django 3.2.15 on 2022-10-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_auto_20221018_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='riderwallet',
            name='rider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_wallet', to='riders.riders'),
        ),
    ]
