# Generated by Django 3.2.15 on 2022-10-05 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('google_api', models.CharField(max_length=500)),
                ('google_captcha_key', models.CharField(max_length=500)),
                ('google_captcha_secret_key', models.CharField(max_length=500)),
                ('facebook_id', models.CharField(max_length=500)),
                ('paystack_sk', models.CharField(max_length=500)),
                ('paystack_pk', models.CharField(max_length=500)),
                ('vapid_sk', models.CharField(max_length=500)),
                ('vapid_pk', models.CharField(max_length=500)),
                ('tinymce_sk', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('approved_waiting_time', models.IntegerField()),
                ('driver_search_radius', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Site Drivers Setting',
                'verbose_name_plural': 'Site Drivers Settings',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Localization',
                'verbose_name_plural': 'Localization',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('logo', stdimage.models.StdImageField(blank=True, upload_to='settings/logo', verbose_name='Logo')),
                ('favicon', stdimage.models.StdImageField(blank=True, upload_to='settings/logo', verbose_name='Favicon')),
                ('copyright', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=165)),
                ('keywords', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('phone_number_II', models.CharField(max_length=255)),
                ('dispute_email', models.EmailField(max_length=254)),
                ('contact_email', models.EmailField(max_length=254)),
                ('playstore_link', models.URLField()),
                ('applestore_link', models.URLField()),
                ('enable_social_login', models.BooleanField(default=False)),
                ('enable_wallet_savings', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SocialSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('pinterest', models.URLField()),
            ],
            options={
                'verbose_name': 'Site Social Account',
                'verbose_name_plural': 'Site Social Accounts',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('v_type', models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('BUSINESS', 'BUSINESS'), ('BUS', 'BUS'), ('MINIVAN', 'MINIVAN'), ('SHARED', 'SHARED')], default='PRIVATE', max_length=50, unique=True)),
                ('v_status', models.CharField(choices=[('PENDING', 'PENDING'), ('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('base_unit', models.DecimalField(decimal_places=2, default=400.0, max_digits=20)),
                ('max_seater', models.PositiveSmallIntegerField(default=4)),
                ('max_luggage', models.PositiveSmallIntegerField(default=2)),
                ('default_rate_by_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_rate_by_location', to='sitesettings.localization')),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
