# Generated by Django 3.2.15 on 2022-10-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20221018_0800'),
        ('riders', '0003_auto_20221018_0800'),
        ('sitesettings', '0004_auto_20221020_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localization',
            name='drivers',
            field=models.ManyToManyField(blank=True, to='drivers.Drivers'),
        ),
        migrations.AlterField(
            model_name='localization',
            name='riders',
            field=models.ManyToManyField(blank=True, to='riders.Riders'),
        ),
    ]
