# Generated by Django 3.2.15 on 2022-10-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0006_localization_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localization',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
