# Generated by Django 4.0.10 on 2023-04-11 17:38

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('interval', models.CharField(blank=True, choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('quaterly', 'quaterly'), ('annually', 'annually')], default='daily', max_length=25, verbose_name='Plan Duration')),
                ('duration', models.PositiveIntegerField(choices=[(1, 'DAY'), (7, 'WEEK'), (30, 'MONTH'), (120, 'QUATER'), (365, 'YEAR')], default=1, verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Ticket Plan',
                'verbose_name_plural': 'Ticket Plans',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TicketSubscription',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired')], default='expired', max_length=15, verbose_name='Ticket Status')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ticket Subscription',
                'verbose_name_plural': 'Tickets Subscription',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
    ]
