# Generated by Django 3.2.15 on 2022-10-05 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivers',
            old_name='approved',
            new_name='is_blocked',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('plan', models.CharField(choices=[('DAILY', 'DAILY'), ('MONTHLY', 'MONTHLY'), ('QUARTER YEAR', 'QUARTER YEAR'), ('HALF YEAR', 'HALF YEAR'), ('YEAR', 'YEAR')], default='DAILY', max_length=20)),
                ('code', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_driver', to='drivers.drivers')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_vehicle_type', to='sitesettings.vehicletype')),
            ],
            options={
                'verbose_name': 'Driver Subscription',
                'verbose_name_plural': 'Drivers Subscriptions',
                'ordering': ['-created', 'active'],
                'managed': True,
            },
        ),
    ]
