# Generated by Django 3.2.15 on 2022-10-25 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20221018_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('unlocked', models.BooleanField(default=False)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_wallet', to='drivers.drivers')),
            ],
            options={
                'verbose_name': 'Driver Wallet',
                'verbose_name_plural': 'Drivers Wallet',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DriverTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], default='PENDING', max_length=25)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_transactions', to='drivers.drivers')),
            ],
            options={
                'verbose_name': 'Driver Transaction History',
                'verbose_name_plural': 'Drivers Transaction Histories',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
