# Generated by Django 4.0.10 on 2023-04-22 23:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('safety', models.IntegerField()),
                ('comfort', models.IntegerField()),
                ('fun', models.IntegerField()),
                ('value_for_money', models.IntegerField()),
                ('accessibility', models.IntegerField()),
                ('wait_time', models.IntegerField()),
                ('note', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup', models.CharField(blank=True, max_length=500)),
                ('p_longitude', models.FloatField(default=0.0)),
                ('p_latitude', models.FloatField(default=0.0)),
                ('dropoff', models.CharField(blank=True, max_length=500)),
                ('d_longitude', models.FloatField(default=0.0)),
                ('d_latitude', models.FloatField(default=0.0)),
                ('distance_km', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('pay_method', models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('WALLET', 'WALLET')], default='CASH', max_length=50, verbose_name='Payment Method')),
                ('driver_arrived', models.DateTimeField(blank=True, null=True)),
                ('depature_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('waiting_time', models.IntegerField(default=0)),
                ('fmt_sec', models.CharField(blank=True, max_length=50, null=True)),
                ('fmt_dist', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('waypoint1_address', models.CharField(blank=True, max_length=500)),
                ('waypoint1_longitude', models.FloatField(default=0.0)),
                ('waypoint1_latitude', models.FloatField(default=0.0)),
                ('waypoint2_address', models.CharField(blank=True, max_length=500)),
                ('waypoint2_longitude', models.FloatField(default=0.0)),
                ('waypoint2_latitude', models.FloatField(default=0.0)),
                ('status', models.CharField(default='SEARCHING FOR DRIVER', max_length=150)),
                ('active', models.BooleanField(default=False)),
                ('car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_type', to='settings.cartype')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
    ]
