# Generated by Django 4.0.10 on 2023-04-22 23:16

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import stdimage.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='reads/cover', verbose_name='Post Cover Photo')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Post Title')),
                ('summary', tinymce.models.HTMLField(blank=True, max_length=255, verbose_name='Post Summary')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Post Keywords')),
                ('content', tinymce.models.HTMLField(verbose_name='Post Content')),
                ('published_date', models.DateField(blank=True, db_index=True, null=True)),
                ('publisher', models.CharField(default='Dropsride Publishers', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=500, verbose_name='Slug')),
                ('draft', models.BooleanField(default=True, verbose_name='Draft/Published')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured Post')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-published_date'],
                'managed': True,
            },
        ),
    ]
