# Generated by Django 4.0.10 on 2023-04-11 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='car/cover', verbose_name='Car Photo')),
                ('title', models.CharField(blank=True, help_text='Lite, Premium, Royalty, Shared', max_length=20, verbose_name='Car Type Name')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True, verbose_name='Slug')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Fixed Maintenance Fee')),
                ('seats', models.IntegerField(default=4)),
            ],
            options={
                'verbose_name': 'Car Type',
                'verbose_name_plural': 'Car Types',
                'ordering': ['-modified', 'title'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tiket_fare', models.DecimalField(db_index=True, decimal_places=2, default=3.22, max_digits=20, verbose_name='Drivers Ticket Fee')),
                ('base_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=20, verbose_name='Base Fare')),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=0.6, max_digits=20, verbose_name='Cost Per KM')),
                ('cost_per_15min', models.DecimalField(decimal_places=2, default=0.32, max_digits=20, verbose_name='Cost Per 15 Minutes')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='currency.states')),
            ],
            options={
                'verbose_name': 'Localization',
                'verbose_name_plural': 'Localizations',
                'ordering': ['state__country_iso', 'state__state'],
                'managed': True,
            },
        ),
    ]
