# Generated by Django 4.0.10 on 2023-04-28 21:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_promo_code_alter_promo_discount_rides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
